import type { Event, SiteSettings } from "@/src/db/schema";

export const defaultSettings: SiteSettings = {
  id: 1,
  coupleNames: "DIANA\n& ERICK",
  heroDateLabel: "9–11 ABRIL",
  heroYearLabel: "2027",
  invitationText: "Te invitamos a compartir con nosotros\nen nuestra boda del 9 al 11 de abril de 2027",
  heroButtonLabel: "VER MÁS",
  rsvpTitle: "RSVP",
  fullNameLabel: "Nombre completo",
  attendancePromptLabel: "Confirma tu asistencia",
  commentLabel: "Comentario adicional",
  submitButtonLabel: "ENVIAR CONFIRMACIÓN",
  confirmationTitle: "¡GRACIAS POR CONFIRMAR!",
  confirmationMessage: "Guardamos tu respuesta. Nos alegra compartir estos días contigo.",
  submitAnotherLabel: "ENVIAR OTRA RESPUESTA",
  rsvpDeadlineDate: "2026-09-18",
  deadlinePrefix: "FAVOR DE RSVP\nHASTA EL",
  deadlineSubtitle: "HORARIOS Y DETALLES A SEGUIR",
  footerText: "Diana & Erick · 2027",
  siteTitle: "Diana & Erick | 9–11 de abril de 2027",
  metaDescription: "Confirma tu asistencia a la boda de Diana y Erick.",
  rsvpEnabled: true,
  rsvpClosedMessage: "Las confirmaciones se encuentran cerradas. Gracias por acompañarnos.",
  updatedAt: new Date(0),
};

export const defaultEvents: Event[] = [
  {
    id: "event-viernes",
    slug: "viernes",
    title: "VIERNES",
    subtitle: "Fiesta de bienvenida",
    date: "2027-04-09",
    startTime: null,
    endTime: null,
    venueName: null,
    address: null,
    mapsUrl: null,
    description: null,
    dressCodeTitle: "DRESS CODE:",
    dressCodeDescription: "CÓMODO Y COLORIDO",
    additionalNote: null,
    iconPath: "/images/event-friday-placeholder.png",
    sortOrder: 1,
    isActive: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
  },
  {
    id: "event-sabado",
    slug: "sabado",
    title: "SÁBADO",
    subtitle: "Iglesia y Recepción",
    date: "2027-04-10",
    startTime: null,
    endTime: null,
    venueName: null,
    address: null,
    mapsUrl: null,
    description: null,
    dressCodeTitle: "DRESS CODE:",
    dressCodeDescription: "MUJERES – VESTIDO LARGO\nHOMBRES – TERNO",
    additionalNote: "PROHIBIDO USAR BLANCO",
    iconPath: "/images/event-saturday-placeholder.png",
    sortOrder: 2,
    isActive: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
  },
  {
    id: "event-domingo",
    slug: "domingo",
  title: "DOMINGO",
    subtitle: "Día de recuperación",
    date: "2027-04-11",
    startTime: null,
    endTime: null,
    venueName: null,
    address: null,
    mapsUrl: null,
    description: null,
    dressCodeTitle: "DRESS CODE:",
    dressCodeDescription: "ROPA DE BAÑO",
    additionalNote: null,
    iconPath: "/images/event-sunday-placeholder.png",
    sortOrder: 3,
    isActive: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
  },
];
