"use client";

import { useState } from "react";
import type { SiteSettings } from "@/src/db/schema";

export function SettingsForm({ settings, adminEmail }: { settings: SiteSettings; adminEmail?: string }) {
  const [values, setValues] = useState({ siteTitle: settings.siteTitle, metaDescription: settings.metaDescription, rsvpEnabled: settings.rsvpEnabled, rsvpClosedMessage: settings.rsvpClosedMessage });
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [isSaving, setIsSaving] = useState(false);
  const update = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(""); setError(""); setIsSaving(true); try { const result = await fetch("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const payload = await result.json() as { message?: string }; if (!result.ok) { setError(payload.message || "No fue posible guardar la configuración."); return; } setMessage("La configuración se guardó correctamente."); } catch { setError("No fue posible guardar la configuración. Intenta nuevamente."); } finally { setIsSaving(false); } };
  return <form className="admin-form settings-form" onSubmit={submit}><div className="admin-form-section"><p className="admin-eyebrow">Identificación</p><h2>SEO y sitio</h2><div className="admin-form-grid admin-form-grid--two"><div className="admin-field"><label htmlFor="siteTitle">Título del sitio</label><input id="siteTitle" value={values.siteTitle} onChange={(e) => update("siteTitle", e.target.value)} required /></div><div className="admin-field"><label htmlFor="metaDescription">Descripción meta</label><textarea id="metaDescription" value={values.metaDescription} onChange={(e) => update("metaDescription", e.target.value)} rows={3} required /></div></div></div><div className="admin-form-section"><p className="admin-eyebrow">Disponibilidad</p><h2>Confirmaciones</h2><label className="admin-toggle admin-toggle--large"><input type="checkbox" checked={values.rsvpEnabled} onChange={(e) => update("rsvpEnabled", e.target.checked)} /><span><strong>Aceptar nuevas confirmaciones</strong><small>Cuando está desactivado, la sección pública muestra el mensaje de cierre.</small></span></label><div className="admin-field"><label htmlFor="rsvpClosedMessage">Mensaje de cierre</label><textarea id="rsvpClosedMessage" value={values.rsvpClosedMessage} onChange={(e) => update("rsvpClosedMessage", e.target.value)} rows={3} required /></div></div><div className="admin-form-section"><p className="admin-eyebrow">Administrador</p><h2>Credenciales</h2><p className="admin-note">Correo configurado: <strong>{adminEmail || "—"}</strong>. Las credenciales se gestionan mediante variables de entorno y el comando de seed.</p></div>{error && <p className="admin-error" role="alert">{error}</p>}{message && <p className="admin-success" role="status">{message}</p>}<button className="admin-button admin-button--primary" type="submit" disabled={isSaving}>{isSaving ? "Guardando…" : "Guardar configuración"}</button></form>;
}
